# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ph', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ph_range', models.BooleanField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
