# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ph',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
