# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170911_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='chain',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
