# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_job_erro'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tksamc_version',
            field=models.IntegerField(choices=[(1, 'Classic TKSA-MC'), (2, 'NTKSA-MC'), (0, 'Both')], default=1),
        ),
    ]
